test-py36:
  stage: test
  image: python:3.6
  script:
    - python3 setup.py install
    - python3 setup.py test

test-py37:
  stage: test
  image: python:3.7
  script:
    - python3 setup.py install
    - python3 setup.py test
